### ISSUE TITLE
Not working on web

### ISSUE THREAD

**Issue by rienkkk** [coskuncay/flutter_chatgpt_api#1]
Hi, thanks for the package!

It seems that the package currently is not working on the web.

In the web console I get the following errors:
`Refused to set unsafe header "cookie"`
and
`Refused to set unsafe header "user-agent"`

The package itself throws the following error:
`ChatGPT failed to refresh auth token: Exception: Failed to refresh access token, token in response is null`

**Comment by coskuncay** [comment]
Our base project is https://github.com/transitive-bullshit/chatgpt-api and v2 published yesterday.
![image](https://user-images.githubusercontent.com/29631083/206423550-2971aab9-268b-469e-a13f-45b5f46d5be0.png)

 Pull requests are welcomed :)

**Comment by itsalfredakku** [comment]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)]
 Unhandled Exception: Exception: ChatGPT failed to refresh auth token: Exception: Failed to refresh access token

#0      ChatGPTApi._refreshAccessToken (package:flutter_chatgpt_api/flutter_chatgpt_api.dart:152:7)
 <asynchronous suspension>
 #1      ChatGPTApi.sendMessage (package:flutter_chatgpt_api/flutter_chatgpt_api.dart:50:25)
 <asynchronous suspension>
#2      _ChatScreenState._buildSubmit.<anonymous closure> (package:neural_ai/screens/chat.screen.dart:110:30)
 <asynchronous suspension>

**Comment by aytunch** [comment]
@coskuncay Hi, thanks for this package.
Is there anything we can do to make this run on flutter web? Is there a limitation on the base project?
